### ISSUE TITLE
Assets and CSS modules ?

### ISSUE THREAD

**Issue by anis-campos** [joernb/react-scripts-with-ssr#1]
Hi,

First, really good work here, these facilitates so much a the starting point of a react-SSR project, thanks a lot !

Everything is working, but there is an issue in my project: the page is really ugly during load.

Origin of the Issue
===

IMHO, the issue comes from this code:
```js
//from src/App.js
import logo from './logo.svg';
import './App.css';
import "bootstrap/dist/css/bootstrap.min.css"
```
I suppose that this imports work pretty well during the hydrate on client side, but doesn't work during SSR.

Solution
===

Inject the CSS and the assets in the HTML  during SSR. But I have no idea of how to do it. Any recommendation ?

**Comment by anis-campos** [comment]
Here screenshots of the issue:

During load 
===
![Screen Shot 2019-04-24 at 10 53 13 AM](https://user-images.githubusercontent.com/5569941/56670082-2c80db00-6680-11e9-970a-bef73d400f19.png)

After Load ( ≈2 sec later)
====
![Screen Shot 2019-04-24 at 10 53 21 AM](https://user-images.githubusercontent.com/5569941/56670086-2f7bcb80-6680-11e9-9325-84b1efb96202.png)

**Comment by flyrev** [comment]
Possibly switch to https://www.npmjs.com/package/isomorphic-style-loader ?
